secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5e8qX9+YB1YJWlG7Sx5gRytgZk6xsNkSCAM2TC127HMSSQDTCZ+Abqa0CzlRadaj0QBEyS0L2XbZYdhSc4XKczuRqQ02Macz76n97o7n8oe7hXl8C96eNSJw2P/OdNOuhpic95NhftczFlo=
config:
  gcp:project: exvs2ib-analyzer
  exvs-shared:artifactRegistryRepo:
    secure: v1:KP2sO7T7aUvq0Uex:LtJwI4sZC0i9/AmxTqobS45IlHWkPIymtaLnCfgzth3XhcU+FHuy
  exvs-shared:pulumiStateBucket:
    secure: v1:p4DDsOtBMQ6T8oSn:FlYZdExZluaVJ//IUrrlPHfeyrOYTewZY6gVbKe9YBku4OoKfcBOIjvu2kHD
  exvs-shared:computeSa:
    secure: v1:pSwvWq5Btyn4T9xU:ME8U55HKMzSLOp8qAElz0UggboMQ0nysjkEl7D43vuEXWxU4O9AwGMoBN5SrLcWrl7XHZ66UPLX58EbkU596ZDja
  exvs-shared:domain: exvs-analyzer.com
  exvs-shared:domainVerificationTxt: google-site-verification=TAXKxm2PncupGRZkk0mBxIxslp_7aZj-w9dxPAi-ObE
  exvs-shared:githubRepo: yuki9431/catalyzer
  gcp:region: asia-northeast1
