secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5eDQTWUGot9QBNaAp0izroIFuFTdE4qYrByGGPxzZegSSQDTCZ+AwaQwWNCA5m1E21p9ntkmIebidXYcIBRWAMY+Hs1XQtL1r94xDEUUk+IN7NnrEvKDgv6Q62vQb8NwjXFpWtE2dHXicwE=
config:
  gcp:project: exvs2ib-analyzer
  gcp:region: asia-northeast1
  exvs-app:serviceName: exvs-analyzer
  exvs-app:cpu: "2"
  exvs-app:memory: 1Gi
  exvs-app:maxInstances: "3"
  exvs-app:domain: www.exvs-analyzer.com
  exvs-app:firestoreDatabase: exvs-analyzer
  exvs-app:sharedStack: organization/exvs-shared/shared
  exvs-app:image:
    secure: v1:PRNQhsUK1id6Rvgb:t6ZPt7ROS932fxfrSPd6D5k27l2xAw4yIqHU10m2OMw524A5YEcoAIfY5VGPdg+Da8m3NHjYjOxD177dQEgatZQBJwTrUn+eu/hMWujMwTV6UmXLqA3lKz7+QnHI1THNOC2Mqhzd122z0fw2yFAbizM4SwAvCocpGW+Smhcf0lc1Q4LAXaW58jeEoiAc5w==
