secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5d1UfBgQCPwxIK7lhY2Nmj9h8+QoNlRNXZtG6hZ2ENgSSADTCZ+A4ORiOrqJM/CSYXSXcH2H9xpwwL5MsJbPD9yXTantitJt/o+fSKysqZ/lVXjn6tyI+Jj19I4AL5/1ioU2U1v7QvQWEg==
config:
  exvs-app:cpu: "2"
  exvs-app:domain: www.exvs-analyzer.com
  exvs-app:firestoreDatabase: exvs-analyzer
  exvs-app:image:
    secure: v1:WyFWXGC+IeFzs/yt:/S6yNswMht0mROtfJ4MLmDEFzoXY8la973gNrSKThH7yBCxJ72x5E9yqPDQ3qkmVDWIfQCv6Dj531si/W+k2Rc1H/C3t94l4u8ezozEUA8EkvqoN2/I223KfyjmzDeYAd0lYOcSEFeyWs1kJlqIbVWJOGEnr+Rjgv1Yg7umYnhpHfBTiQBcdnpHfsV7W7g==
  exvs-app:maxInstances: "3"
  exvs-app:memory: 1Gi
  exvs-app:serviceName: exvs-analyzer
  exvs-app:sharedStack: organization/exvs-shared/shared
  gcp:project: exvs2ib-analyzer
  gcp:region: asia-northeast1
