encryptionsalt: v1:evUdMCCS5y8=:v1:/OISA4XjAeNSfiWM:dpR57gY0VOZJwLVX4naIh01vl/GXDg==
config:
  gcp:project:
    secure: v1:GFZ/rFuC+i0R/bSv:NNxS64NTcMbplD9tvMzrMcd5mprAYX+Q5EByqXsk5dE=
  gcp:region: asia-northeast1
  exvs-app:cpu: "1"
  exvs-app:memory: 512Mi
  exvs-app:maxInstances: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:image:
    secure: v1:DXcoGWgIQllZXcvL:2jSbQiGtn5eJcHYgxd28I1N/K3k29xGz/w2Wf/oHhnuoZ3K0LJiE7BwlnTsHkNWIszg/kWDWJg2mv8UWdrEKTxQBABev+GSuI25AGC81stQuVT5apf5m0cEsqA4kXDVjxv8Fb25gNNIgMcergKLXJo+7Tc/1VzXMcN2R58u58KQEe8bKfC+YlE/vZjNtlA==
  exvs-app:gcsBucket:
    secure: v1:ZpepUFqv5KJMeSu1:0iAEyxxqllexQbeTezIhRPKvwR+2/sW5VY9iqpRWtWDeidp+gw==
  exvs-app:sharedStack: organization/exvs-shared/shared
  exvs-app:serviceName: stg-exvs-analyzer
  exvs-app:firestoreDatabase: exvs-analyzer
