encryptionsalt: v1:evUdMCCS5y8=:v1:/OISA4XjAeNSfiWM:dpR57gY0VOZJwLVX4naIh01vl/GXDg==
config:
  gcp:project:
    secure: v1:GFZ/rFuC+i0R/bSv:NNxS64NTcMbplD9tvMzrMcd5mprAYX+Q5EByqXsk5dE=
  gcp:region: asia-northeast1
  exvs-app:cpu: "1"
  exvs-app:memory: 512Mi
  exvs-app:maxInstances: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:image:
    secure: v1:DIxOgY1Nl4TFWlUW:qorrZbozKXirm1mjw5ZAnMwzMV6AW2oZGjWiarFoFERweBw38FpGYK69yq83o9J4bSYsHcxfPf1bt2qjdPgN11m+NnZhhUIF3OP+X5KELttkRYCjxZUdDqPn7TIBKqEmoRKNJhWnVE8u4KUvJkYM3jsYkiAPPSuulNzbZnApf1ayox1ZRMHp42CwpaqV6Q==
  exvs-app:gcsBucket:
    secure: v1:ZpepUFqv5KJMeSu1:0iAEyxxqllexQbeTezIhRPKvwR+2/sW5VY9iqpRWtWDeidp+gw==
  exvs-app:sharedStack: organization/exvs-shared/shared
  exvs-app:serviceName: stg-exvs-analyzer
  exvs-app:firestoreDatabase: exvs-analyzer
