secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5WDA7usIHCU/rNrKnSr+O2Xzg+vXaTCsa5NSOw6loLISSQDTCZ+A4B7OnFsieoFe5+hdATGg6IDYWfj2OxYlVBH4gDymLO8WhUw5UYJ5YlZsazRt77LU3cBiJL+jnrYBIl1IdyxBbkqVgkU=
config:
  exvs-app:cpu: "1"
  exvs-app:domain: stg.exvs-analyzer.com
  exvs-app:firestoreDatabase: exvs-analyzer
  exvs-app:image:
    secure: v1:5tLyez9fE7gxFk1i:o8ohhm3j/9XvuKp1LCUxJGVdQsYVAE5ESGK6pj69UdwgosrmV3tdq8h7rCOkJfMLSnvcjZi2obEokyn/zf7C0L4nqKayq8YwN5qPCB4yVzzBEUCu7uslKCoXS6hOgM1YchtvnBL0Dz1qE+tx8v47AcozGY5JZ+svFGXrKEJFRHRtBYJfs733qw1qyQtsWg==
  exvs-app:maxInstances: "1"
  exvs-app:memory: 512Mi
  exvs-app:serviceName: stg-exvs-analyzer
  exvs-app:sharedStack: organization/exvs-shared/shared
  gcp:project: exvs2ib-analyzer
  gcp:region: asia-northeast1
