secretsprovider: gcpkms://projects/exvs2ib-analyzer/locations/asia-northeast1/keyRings/pulumi-secrets/cryptoKeys/pulumi-state
encryptedkey: CiQAll9D5d1UfBgQCPwxIK7lhY2Nmj9h8+QoNlRNXZtG6hZ2ENgSSADTCZ+A4ORiOrqJM/CSYXSXcH2H9xpwwL5MsJbPD9yXTantitJt/o+fSKysqZ/lVXjn6tyI+Jj19I4AL5/1ioU2U1v7QvQWEg==
config:
  exvs-app:cpu: "2"
  exvs-app:domain: www.exvs-analyzer.com
  exvs-app:firestoreDatabase: exvs-analyzer
  exvs-app:image:
    secure: v1:A6Wbcq0nvhxY9lJz:SGdncc2ef9XxZnkh5/3J1/oR+3lQIMTl+8U8Ry/wsW8nw4i5SGg5qKv218nxMDrXj9COdGGoZHlNj/xUwmI3X3Viaj7H9HkTX3qObJCCSA8LCLwOuxYQRq7VhTOxXNFqhE3GmrXnANm2dY0kKjl+8zdopppMCWkXtBnbzTzhYkKDxbxwNKbCqgaxUChlyg==
  exvs-app:maxInstances: "3"
  exvs-app:memory: 1Gi
  exvs-app:serviceName: exvs-analyzer
  exvs-app:sharedStack: organization/exvs-shared/shared
  gcp:project: exvs2ib-analyzer
  gcp:region: asia-northeast1
